CREATE TABLE "NOVEDADES" (
    "ID_NOVEDAD" NUMBER(7,0) GENERATED ALWAYS AS IDENTITY, 
    "COD_CONCEPTO" NUMBER(7,0) NOT NULL,
    "MONTO" NUMBER(12,2) NOT NULL, 
    "CEDULA" VARCHAR2(20) NOT NULL,
    "FECHA_INI" DATE NOT NULL,
    "FECHA_FIN" DATE,
    "ESTADO" VARCHAR2(10) DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'PROCESADO')),
    "USUARIO_CREACION" VARCHAR2(50), 
    "FECHA_CREACION" TIMESTAMP DEFAULT SYSTIMESTAMP, 
    CONSTRAINT "PK_NOVEDADES" PRIMARY KEY ("ID_NOVEDAD"),
    CONSTRAINT "CHK_FECHAS" CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INI)
);

CREATE TABLE "LIQUIDACION" (
    "COD_LIQUIDACION" NUMBER(7,0) GENERATED ALWAYS AS IDENTITY,
    "ID_EMPLEADO" NUMBER(7,0) NOT NULL,
    "FECHA_LIQUIDACION" DATE NOT NULL,
    "PERIODO_INICIO" DATE NOT NULL, 
    "PERIODO_FIN" DATE NOT NULL, 
    "PERCEPCIONES" NUMBER(12,2) DEFAULT 0,
    "DEDUCCIONES" NUMBER(12,2) DEFAULT 0,
    "NETO" NUMBER(12,2) NOT NULL,
    "ESTADO" VARCHAR2(15) DEFAULT 'BORRADOR' CHECK (ESTADO IN ('BORRADOR', 'APROBADO', 'PAGADO', 'CANCELADO')),
    "USUARIO_PROCESO" VARCHAR2(50),
    "FECHA_PROCESO" TIMESTAMP,
    PRIMARY KEY ("COD_LIQUIDACION"),
    CONSTRAINT "CHK_PERIODO" CHECK (PERIODO_FIN > PERIODO_INICIO),
    CONSTRAINT "CHK_NETO" CHECK (NETO = PERCEPCIONES - DEDUCCIONES)
);

CREATE TABLE "PERIODOS_NOMINA" (
    "COD_PERIODO" NUMBER(7,0) GENERATED ALWAYS AS IDENTITY,
    "FECHA_INICIO" DATE NOT NULL,
    "FECHA_FIN" DATE NOT NULL,
    "DESCRIPCION" VARCHAR2(100),
    "ESTADO" VARCHAR2(20) DEFAULT 'ABIERTO' CHECK (ESTADO IN ('ABIERTO', 'CERRADO', 'PROCESADO')),
    "FECHA_PAGO" DATE NOT NULL,
    PRIMARY KEY ("COD_PERIODO"),
    CONSTRAINT "UK_PERIODO_FECHAS" UNIQUE (FECHA_INICIO, FECHA_FIN)
);

CREATE TABLE "AUDITORIA_NOMINA" (
    "ID_AUDITORIA" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY,
    "TABLA_AFECTADA" VARCHAR2(50) NOT NULL,
    "ID_REGISTRO" NUMBER(10,0) NOT NULL,
    "ACCION" VARCHAR2(10) NOT NULL CHECK (ACCION IN ('INSERT', 'UPDATE', 'DELETE')),
    "USUARIO" VARCHAR2(50) NOT NULL,
    "FECHA" TIMESTAMP DEFAULT SYSTIMESTAMP,
    "VALOR_ANTERIOR" CLOB,
    "VALOR_NUEVO" CLOB,
    PRIMARY KEY ("ID_AUDITORIA")
);

  CREATE TABLE "LIQUIDACION_DETALLE" 
   (	"ID_DETALLE" NUMBER(7,0), 
	"COD_LIQUIDACION" NUMBER(7,0) NOT NULL ENABLE, 
	"COD_CONCEPTO" NUMBER(7,0) NOT NULL ENABLE, 
	"MONTO" NUMBER(10,2) NOT NULL ENABLE, 
	"TIPO_CONCEPTO" VARCHAR2(10), 
	 PRIMARY KEY ("ID_DETALLE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "LIQUIDACION_DETALLE" ADD CONSTRAINT "FK_DETALLE_CONCEPTO" FOREIGN KEY ("COD_CONCEPTO")
	  REFERENCES "CONCEPTOS" ("COD_CONCEPTO") ENABLE;
  ALTER TABLE "LIQUIDACION_DETALLE" ADD CONSTRAINT "FK_DETALLE_LIQUIDACION" FOREIGN KEY ("COD_LIQUIDACION")
	  REFERENCES "LIQUIDACION" ("COD_LIQUIDACION") ENABLE;


CREATE TABLE LIQUIDACION_DETALLE (
    ID_DETALLE       NUMBER(7,0),
    COD_LIQUIDACION  NUMBER(7,0) NOT NULL,
    COD_CONCEPTO     NUMBER(7,0) NOT NULL,
    MONTO            NUMBER(10,2) NOT NULL,
    TIPO_CONCEPTO    VARCHAR2(10),
    CONSTRAINT PK_LIQUIDACION_DETALLE PRIMARY KEY (ID_DETALLE)
);

ALTER TABLE LIQUIDACION_DETALLE 
ADD CONSTRAINT FK_DETALLE_LIQUIDACION 
FOREIGN KEY (COD_LIQUIDACION)
REFERENCES LIQUIDACION (COD_LIQUIDACION);


CREATE INDEX "IDX_NOVEDADES_EMPLEADO" ON "NOVEDADES" ("CEDULA", "FECHA_INI", "FECHA_FIN");
CREATE INDEX "IDX_LIQUIDACION_EMPLEADO" ON "LIQUIDACION" ("ID_EMPLEADO", "FECHA_LIQUIDACION");
CREATE INDEX "IDX_LIQ_DETALLE_CONCEPTO" ON "LIQUIDACION_DETALLE" ("COD_CONCEPTO");


-- faltan los conceptos

ALTER TABLE LIQUIDACION_DETALLE 
ADD CONSTRAINT FK_DETALLE_CONCEPTO 
FOREIGN KEY (COD_CONCEPTO)
REFERENCES CONCEPTOS (COD_CONCEPTO);


CREATE TABLE "CONCEPTOS" (
    "COD_CONCEPTO" NUMBER(7,0) GENERATED ALWAYS AS IDENTITY,
    "DESCRIPCION" VARCHAR2(100) NOT NULL,
    "FIJO" CHAR(1) DEFAULT 'N' CHECK (FIJO IN ('S', 'N')),
    "PORCENTAJE" NUMBER(5,2) CHECK (PORCENTAJE BETWEEN 0 AND 100),
    "DEB_CREDITO" CHAR(1) NOT NULL CHECK (DEB_CREDITO IN ('D', 'C')),
    "IPS" CHAR(1) DEFAULT 'N' CHECK (IPS IN ('S', 'N')),
    "TIPO" VARCHAR2(20) NOT NULL CHECK (TIPO IN ('SALARIAL', 'NO_SALARIAL', 'BONO', 'DESCUENTO')),
    "APLICA_IMPUEStO" CHAR(1) DEFAULT 'N' CHECK (APLICA_IMPUESTO IN ('S', 'N')),
    "CODIGO_LEGAL" VARCHAR2(20), 
    "VIGENTE" CHAR(1) DEFAULT 'S' CHECK (VIGENTE IN ('S', 'N')),
    PRIMARY KEY ("COD_CONCEPTO")
);
