CREATE TABLE PERIODOS_NOMINA (
    ID_PERIODO      NUMBER(5) PRIMARY KEY,
    MES             NUMBER(2) NOT NULL,
    ANIO            NUMBER(4) NOT NULL,
    FECHA_INICIO    DATE NOT NULL,
    FECHA_FIN       DATE NOT NULL,
    ESTADO          VARCHAR2(20) DEFAULT 'PENDIENTE' -- ACTIVO, CERRADO, etc.
);

CREATE TABLE LIQUIDACION (
    ID_LIQUIDACION  NUMBER(10) PRIMARY KEY,
    ID_EMPLEADO     NUMBER(7) NOT NULL,
    ID_PERIODO      NUMBER(5) NOT NULL,
    FECHA_LIQUIDACION DATE DEFAULT SYSDATE,
    TOTAL_HABER     NUMBER(12,2),
    TOTAL_DEBE      NUMBER(12,2),
    TOTAL_NETO      NUMBER(12,2),
    
    CONSTRAINT FK_LIQ_EMPLEADO FOREIGN KEY (ID_EMPLEADO) 
        REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_LIQ_PERIODO FOREIGN KEY (ID_PERIODO) 
        REFERENCES PERIODOS_NOMINA(ID_PERIODO)
);

CREATE TABLE CONCEPTOS (
    ID_CONCEPTO         NUMBER(6) PRIMARY KEY,
    DESCRIPCION         VARCHAR2(100) NOT NULL,
    TIPO                VARCHAR2(1) CHECK (TIPO IN ('H','D')), -- Haber o Debe
    AFECTA_IPS          CHAR(1) DEFAULT 'N' CHECK (AFECTA_IPS IN ('S','N')),
    AFECTA_AGUINALDO    CHAR(1) DEFAULT 'N' CHECK (AFECTA_AGUINALDO IN ('S','N')),
    RECURRENTE          CHAR(1) DEFAULT 'S' CHECK (RECURRENTE IN ('S','N'))
);


CREATE TABLE LIQUIDACION_DETALLE (
    ID_LIQUIDACION  NUMBER(10),
    ID_CONCEPTO     NUMBER(6),
    MONTO           NUMBER(12,2),
    TIPO            VARCHAR2(1) CHECK (TIPO IN ('H','D')), -- H: haber, D: debe

    CONSTRAINT PK_LIQ_DETALLE PRIMARY KEY (ID_LIQUIDACION, ID_CONCEPTO),
    CONSTRAINT FK_LIQ_DET_LIQ FOREIGN KEY (ID_LIQUIDACION) 
        REFERENCES LIQUIDACION(ID_LIQUIDACION),
    CONSTRAINT FK_LIQ_DET_CONC FOREIGN KEY (ID_CONCEPTO) 
        REFERENCES CONCEPTOS(ID_CONCEPTO)
);

CREATE TABLE NOVEDADES (
    ID_NOVEDAD      NUMBER(10) PRIMARY KEY,
    ID_EMPLEADO     NUMBER(7) NOT NULL,
    ID_PERIODO      NUMBER(5) NOT NULL,
    ID_CONCEPTO     NUMBER(6) NOT NULL,
    MONTO           NUMBER(12,2) NOT NULL,

    CONSTRAINT FK_NOV_EMPLEADO FOREIGN KEY (ID_EMPLEADO) 
        REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_NOV_PERIODO FOREIGN KEY (ID_PERIODO) 
        REFERENCES PERIODOS_NOMINA(ID_PERIODO),
    CONSTRAINT FK_NOV_CONCEPTO FOREIGN KEY (ID_CONCEPTO) 
        REFERENCES CONCEPTOS(ID_CONCEPTO)
);

CREATE TABLE AUDITORIA_NOMINA (
    ID_AUDITORIA    NUMBER(10) PRIMARY KEY,
    ID_EMPLEADO     NUMBER(7) NOT NULL,
    ID_PERIODO      NUMBER(5) NOT NULL,
    ACCION          VARCHAR2(50),
    FECHA_ACCION    DATE DEFAULT SYSDATE,
    USUARIO         VARCHAR2(30),

    CONSTRAINT FK_AUD_EMPLEADO FOREIGN KEY (ID_EMPLEADO) 
        REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_AUD_PERIODO FOREIGN KEY (ID_PERIODO) 
        REFERENCES PERIODOS_NOMINA(ID_PERIODO)
);

CREATE SEQUENCE SEQ_ID_PERIODO START WITH 1;
CREATE SEQUENCE SEQ_ID_LIQUIDACION START WITH 1;
CREATE SEQUENCE SEQ_ID_CONCEPTO START WITH 1;
CREATE SEQUENCE SEQ_ID_LIQUIDACION_DETALLE START WITH 1;
CREATE SEQUENCE SEQ_ID_NOVEDAD START WITH 1;
CREATE SEQUENCE SEQ_ID_AUDITORIA START WITH 1;










--------------------------------------------------------
CREATE TABLE HIJOS (
    ID_HIJO         NUMBER(10) PRIMARY KEY,
    ID_EMPLEADO     NUMBER(7) NOT NULL,
    FECHA_NAC       DATE NOT NULL,

    CONSTRAINT FK_HIJOS_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE PARAMETROS_NOMINA (
    CLAVE        VARCHAR2(50) PRIMARY KEY,
    VALOR_NUM    NUMBER(12,2),
    VALOR_CHAR   VARCHAR2(100)
);

-- Inserción del salario mínimo actual
INSERT INTO PARAMETROS_NOMINA (CLAVE, VALOR_NUM) VALUES ('SALARIO_MINIMO', 2800000);
